PXB-3745: require ARCH in pxb v2 docker runners
- run-build + run-test take ARCH as a required argument (fail-closed)
- arch-aware S3 tarball selectors and libaio path; x86_64 selection is
  byte-identical to the previous literal
- vault token retry honors success on the last attempt
- XBCLOUD_CREDENTIALS quoting hardened for the container sh -c script

diff --git a/pxb/v2/docker/run-build b/pxb/v2/docker/run-build
--- a/pxb/v2/docker/run-build
+++ b/pxb/v2/docker/run-build
@@ -1,4 +1,12 @@
 #!/bin/bash
+#
+# Build PXB inside a pxc-build container.
+#
+# Usage: ./docker/run-build <SOURCE_IMAGE> <ARCH>
+#   SOURCE_IMAGE  docker tag (oraclelinux:9, ubuntu:noble, asan, etc.)
+#   ARCH          x86_64 | aarch64   (REQUIRED, no default)
+#
+# Image pulled: public.ecr.aws/e7j3v3n0/pxc-build:<distro>[-aarch64]
 
 set -o errexit
 set -o xtrace
@@ -6,6 +14,13 @@ set -o xtrace
 ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
 SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
 SOURCE_IMAGE=${1:-oraclelinux:9}
+ARCH=${2:?ARCH is required (x86_64 or aarch64)}
+
+case "${ARCH}" in
+    x86_64)  ARCH_SUFFIX="" ;;
+    aarch64) ARCH_SUFFIX="-aarch64" ;;
+    *) echo "ERROR: unsupported ARCH='${ARCH}', expected x86_64 or aarch64" >&2; exit 1 ;;
+esac
 
 if [[ ${SOURCE_IMAGE} == 'asan' ]]; then
     SOURCE_IMAGE='oraclelinux:9'
@@ -16,7 +31,7 @@ docker run --rm \
     --cap-add SYS_PTRACE \
     --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxb \
     --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
-    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
+    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-}${ARCH_SUFFIX} \
     sh -c "
     set -o errexit
     set -o xtrace
