Jenkins job fix for pathname (#1588)
Fixed - Sporadic failures on Jenkins due to ProxySQL tarball file missing

diff --git a/proxysql/test-proxysql b/proxysql/test-proxysql
--- a/proxysql/test-proxysql
+++ b/proxysql/test-proxysql
@@ -119,7 +119,25 @@ elif [ -f /usr/bin/apt ]; then
 fi
 
 pushd ${WORKDIR_ABS}/WORKDIR
-sudo tar -xzf $WORKDIR_ABS/proxysql*glibc*.tar.gz -C ${WORKDIR_ABS}/PROXY_ADMIN
+unset PROXY_TAR_FILENAME
+COPY_TIMEOUT=60
+
+for X in $(seq 0 $COPY_TIMEOUT); do
+  PROXY_TAR_FILENAME=$(ls -1 $WORKDIR_ABS/ | grep -E "proxysql.*.glibc.*.tar.gz")
+  if [ -f $WORKDIR_ABS/$PROXY_TAR_FILENAME ]; then
+    sudo tar -xzf $WORKDIR_ABS/$PROXY_TAR_FILENAME -C ${WORKDIR_ABS}/PROXY_ADMIN
+    break;
+  else
+    echo "Waiting for file to copy"
+  fi
+
+  if [ $X -eq $COPY_TIMEOUT ]; then
+    echo "Timout exceeded. Failed to copy proxysql tarball within time limit"
+    exit 1
+  fi
+  sleep 1
+done
+
 for file in proxysql-admin proxysql-admin-common proxysql-login-file proxysql-common percona-scheduler-admin; do
   sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/usr/bin/$file ${WORKDIR_ABS}/WORKDIR/$file
 done;
