PXC-3364: Adding MTR params

diff --git a/pxc/local/test-binary-pxc57 b/pxc/local/test-binary-pxc57
--- a/pxc/local/test-binary-pxc57
+++ b/pxc/local/test-binary-pxc57
@@ -67,23 +67,113 @@ if [[ "${DEFAULT_TESTING}" != "no" ]]; then
     else
         MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}"
     fi
-
-  MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
-        --parallel=${PARALLEL} \
-        --result-file \
-        ${MTR_ARGS} \
-        --force --xml-report=${WORKDIR_ABS}/mtr.xml \
-        --max-test-fail=0 \
-        --suite-timeout=9999 \
-        --testcase-timeout=${TESTCASE_TIMEOUT} \
-        | tee ${WORKDIR_ABS}/mtr.output || status=$?
+    if [ -z $FULL_MTR ]; then
+        # galera suite
+        if echo "$MTR_SUITES" | grep -Eq "galera[ ,]"; then
+           mkdir var1
+           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
+              --parallel=${PARALLEL} \
+              --result-file --suite=galera \
+              ${MTR_ARGS} \
+              --force --xml-report=${WORKDIR_ABS}/galera_mtr.xml \
+              --max-test-fail=0 \
+              --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
+              --port-group-size=20 --vardir=var1 \
+              --testcase-timeout=${TESTCASE_TIMEOUT} \
+              | tee ${WORKDIR_ABS}/galera_mtr.output || status=$?
+    
+            killall -9 mysqld || true
+		    sed -i '1d' ${WORKDIR_ABS}/galera_mtr.xml
+		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/galera_mtr.xml
+		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/galera_mtr.xml > ${WORKDIR_ABS}/galera_mtr.tmp
+		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/galera_mtr.tmp >  ${WORKDIR_ABS}/galera_mtr1.tmp
+		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/galera_mtr1.tmp >  ${WORKDIR_ABS}/galera_junit.xml
+		    rm -f ${WORKDIR_ABS}/galera_mtr*.tmp ${WORKDIR_ABS}/galera_mtr.xml
+        fi
+    
+        # galera_3nodes suite
+        if echo "$MTR_SUITES" | grep -Eq "galera_3nodes"; then
+           mkdir var2
+           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
+              --parallel=${PARALLEL} \
+              --result-file --suite=galera_3nodes \
+              ${MTR_ARGS} \
+              --force --xml-report=${WORKDIR_ABS}/galera3_mtr.xml \
+              --max-test-fail=0 \
+              --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
+              --port-group-size=20 --vardir=var2 \
+              --testcase-timeout=${TESTCASE_TIMEOUT} \
+              | tee ${WORKDIR_ABS}/galera3_mtr.output || status=$?
+    
+            killall -9 mysqld || true
+		    sed -i '1d' ${WORKDIR_ABS}/galera3_mtr.xml
+		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/galera3_mtr.xml
+		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/galera3_mtr.xml > ${WORKDIR_ABS}/galera3_mtr.tmp
+		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/galera3_mtr.tmp >  ${WORKDIR_ABS}/galera3_mtr1.tmp
+		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/galera3_mtr1.tmp >  ${WORKDIR_ABS}/galera3_junit.xml
+		    rm -f ${WORKDIR_ABS}/galera3_mtr*.tmp ${WORKDIR_ABS}/galera3_mtr.xml
+        fi
+    
+        # sys_vars suite
+        if echo "$MTR_SUITES" | grep -Eq "sys_vars"; then
+           mkdir var3
+           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
+              --parallel=${PARALLEL} \
+              --result-file --suite=sys_vars \
+              ${MTR_ARGS} \
+              --force --xml-report=${WORKDIR_ABS}/sys_vars.xml \
+              --max-test-fail=0 \
+              --suite-timeout=9999 --parallel $PARALLEL_RUN \
+              --port-group-size=20 --vardir=var3 \
+              --testcase-timeout=${TESTCASE_TIMEOUT} \
+              | tee ${WORKDIR_ABS}/sys_vars.output || status=$?
+    		  
+            killall -9 mysqld || true
+		    sed -i '1d' ${WORKDIR_ABS}/sys_vars.xml
+		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/sys_vars.xml
+		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/sys_vars.xml > ${WORKDIR_ABS}/sys_vars.tmp
+		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/sys_vars.tmp >  ${WORKDIR_ABS}/sys_vars1.tmp
+		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/sys_vars1.tmp >  ${WORKDIR_ABS}/sys_vars_junit.xml
+		    rm -f ${WORKDIR_ABS}/sys_vars*.tmp ${WORKDIR_ABS}/sys_vars.xml
+        fi
+    else
+        echo "Running full MTR"
+        mkdir var1
+        MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
+           --parallel=${PARALLEL} \
+           --result-file \
+           ${MTR_ARGS} \
+           --force --xml-report=${WORKDIR_ABS}/mtr.xml \
+           --max-test-fail=0 \
+           --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
+           --port-group-size=20 --vardir=var1 \
+           --testcase-timeout=${TESTCASE_TIMEOUT} \
+           | tee ${WORKDIR_ABS}/mtr.output || status=$?
+    
+        killall -9 mysqld || true
+	    sed -i '1d' ${WORKDIR_ABS}/mtr.xml
+	    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/mtr.xml
+	    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/mtr.xml > ${WORKDIR_ABS}/junit.tmp
+	    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/junit.tmp >  ${WORKDIR_ABS}/junit1.tmp
+	    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/junit1.tmp >  ${WORKDIR_ABS}/junit.xml
+	    rm -f ${WORKDIR_ABS}/junit*.tmp ${WORKDIR_ABS}/mtr.xml
+    fi
+  #MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
+  #      --parallel=${PARALLEL} \
+  #      --result-file \
+  #      ${MTR_ARGS} \
+  #      --force --xml-report=${WORKDIR_ABS}/mtr.xml \
+  #      --max-test-fail=0 \
+  #      --suite-timeout=9999 \
+  #      --testcase-timeout=${TESTCASE_TIMEOUT} \
+  #      | tee ${WORKDIR_ABS}/mtr.output || status=$?
   
-  sed -i '1d' ${WORKDIR_ABS}/mtr.xml
-  sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/mtr.xml
-  sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/mtr.xml > ${WORKDIR_ABS}/junit.tmp
-  sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/junit.tmp >  ${WORKDIR_ABS}/junit1.tmp
-  sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/junit1.tmp >  ${WORKDIR_ABS}/junit.xml
-  rm -f ${WORKDIR_ABS}/junit*.tmp ${WORKDIR_ABS}/mtr.xml
+  #sed -i '1d' ${WORKDIR_ABS}/mtr.xml
+  #sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/mtr.xml
+  #sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/mtr.xml > ${WORKDIR_ABS}/junit.tmp
+  #sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/junit.tmp >  ${WORKDIR_ABS}/junit1.tmp
+  #sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/junit1.tmp >  ${WORKDIR_ABS}/junit.xml
+  #rm -f ${WORKDIR_ABS}/junit*.tmp ${WORKDIR_ABS}/mtr.xml
 fi
 
 exit $status
