Kill socat and mysqld leftovers

diff --git a/pxc/local/test-binary-pxc-parallel-mtr b/pxc/local/test-binary-pxc-parallel-mtr
--- a/pxc/local/test-binary-pxc-parallel-mtr
+++ b/pxc/local/test-binary-pxc-parallel-mtr
@@ -25,6 +25,13 @@ set -o xtrace
 # Execution mode. If suites should be executed one by one, or all together
 EXECUTE_SUITES_ONE_BY_ONE=1
 
+# Some galera tests if failed, leave socat hanging. It consumes 100% CPU and blocks ports.
+# If there are any mysqld hanging, kill them as well
+function kill_socat_and_mysqld() {
+    # It may happen that pid found by grep disappears in the meantime, so ||:
+    pgrep -f socat | xargs -r kill -9 2>/dev/null || true
+    pgrep -f mysqld | xargs -r kill -9 2>/dev/null || true
+}
 
 function execute() {
     local suites=$1
@@ -69,7 +76,8 @@ function execute() {
     which rsync
     rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${worker} $PWD/mtr_var
 
-    killall -9 mysqld || true
+    kill_socat_and_mysqld
+
     rm -rf $PWD/var_${worker}
 
     df -h
@@ -361,7 +369,8 @@ if [[ $UNIT_TESTS == "1" ]]; then
     ln -s $PWD/var $PWD/var_${suiteNoSlash}
     rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} $PWD/mtr_var
 
-    killall -9 mysqld || true
+    kill_socat_and_mysqld
+
     rm -rf $PWD/var_${suiteNoSlash}
 
     df -h
@@ -562,6 +571,8 @@ if [[ "${CI_FS_MTR}" = 'yes' ]]; then
 
     rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' /tmp/ci_disk_dir $PWD/mtr_var
 
+    kill_socat_and_mysqld
+
     end=`date +%s`
     runtime=$((end-start))
     echo KH,SUITE_TOTAL,CI_FS_tests,time,$runtime
@@ -597,7 +608,8 @@ if [[ -n "${MTR_STANDALONE_TESTS}" ]]; then
     ln -s $PWD/var $PWD/var_${suiteNoSlash}
     rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} $PWD/mtr_var
 
-    killall -9 mysqld || true
+    kill_socat_and_mysqld
+
     rm -rf $PWD/var_${suiteNoSlash}
 
     df -h
